import csv

cards = [
  {
    'cardid': 20059,
    'name': 'Darkfire Sacrifice',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 0,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': 'Destroy a friendly minion. Your next minion costs 2 less.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 308,
    'name': 'Abyssal Crawler',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 1,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text':
      'At the end of your turn, turn a nearby space into <b>Shadow Creep</b>.',
    'attack': 2,
    'health': 1,
    'spirit': 0
  },
  {
    'cardid': 20226,
    'name': 'Aphotic Drain',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': 'Destroy a friendly minion to restore 5 Health to your General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20376,
    'name': 'Demonic Conversion',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': "Draw a minion from your opponent's deck. It gains +1/+1.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 331,
    'name': 'Furiosa',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': '<b>Blood Surge</b>: Friendly Wraithlings gain +1/+1.',
    'attack': 1,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 20070,
    'name': 'Grasp of Agony',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      'Choose an enemy minion. When it dies, it deals 3 damage to enemies around it.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30005,
    'name': 'Horn of the Forsaken',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 1,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text':
      'Whenever your General deals damage, summon a 1/1 Wraithling nearby your General.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 20272,
    'name': 'Inkling Surge',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      'Summon a 1/1 Wraithling. If you have another Wraithling, draw a card.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20269,
    'name': 'Nethermeld',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Teleport ANY minion to friendly <b>Shadow Creep</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20356,
    'name': 'Painful Pluck',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      '<b>Intensify</b>: Turn 1 random space into <b>Shadow Creep</b>, prioritizing spaces under enemy minions.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20052,
    'name': 'Void Pulse',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': 'Deal 2 damage to enemy General. Restore 3 Health to your General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 313,
    'name': 'Blood Siren',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': '<b>Opening Gambit</b>: Give a nearby enemy -2 attack this turn.',
    'attack': 3,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 359,
    'name': 'Carrion Collector',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      '<b>Dying Wish</b>: Lower the cost of all minions with <b>Dying Wish</b> in your deck and action bar by 1.',
    'attack': 1,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20271,
    'name': 'Choking Tendrils',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': 'Destroy an enemy minion on friendly <b>Shadow Creep</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20166,
    'name': 'Consuming Rebirth',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      'Destroy a friendly minion. At the end of your turn, re-summon it on the same space and give it +1/+1.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20049,
    'name': 'Daemonic Lure',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text': 'Deal 1 damage to an enemy minion and teleport it anywhere.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 316,
    'name': 'Darkspine Elemental',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': 'Double the damage dealt by friendly <b>Shadow Creep</b>.',
    'attack': 1,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20333,
    'name': 'Deathmark',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      'Deal 1 damage to an enemy minion. After it is attacked this turn, destroy it.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20204,
    'name': 'Echoing Shriek',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Transform ALL minions that cost 2 or less into 1/1 Wraithlings.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 363,
    'name': 'Gibbet',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      'Whenever this attacks an enemy minion, destroy that minion and summon a Gibbet on that space.',
    'attack': 1,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 317,
    'name': 'Gloomchaser',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text':
      '<b>Opening Gambit</b>: Summon a 1/1 Wraithling in a random nearby space.',
    'attack': 2,
    'health': 2,
    'spirit': 0
  },
  {
    'cardid': 326,
    'name': 'Gor',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Battle Pet',
    'cost': 2,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': '<b>Dying Wish</b>: Re-summon this minion in a random corner.',
    'attack': 1,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20200,
    'name': 'Inkhorn Gaze',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      'Deal 2 damage to a minion. If it dies this turn, put a random Battle Pet into your action bar.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20199,
    'name': 'Lurking Fear',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      'Lower the cost of all minions with <b>Dying Wish</b> in your action bar and deck by 1.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 351,
    'name': 'Nightmare Operant',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': 'Mech',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': '<b>Dying Wish</b>: Shuffle a MECHAZ0R into your deck.',
    'attack': 3,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 337,
    'name': 'Nocturne',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Arcanyst',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Whenever you make Shadow Creep or a Wraithling, instead make both.',
    'attack': 2,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 327,
    'name': 'Ooz',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Battle Pet',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      'Whenever this minion takes damage, turn a space occupied by an enemy into <b>Shadow Creep</b>.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 339,
    'name': 'Phantasm',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      'Whenever your opponent summons a minion, give a minion in your action bar +1 Attack.',
    'attack': 3,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 20243,
    'name': 'Punish',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': 'Destroy a damaged minion.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20273,
    'name': 'Shadowstalk',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': 'Summon a Wraithling behind each enemy.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20071,
    'name': 'Soulshatter Pact',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text': 'Give all friendly minions +2 Attack this turn.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 30014,
    'name': 'Spectral Blade',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      'Your General gains +2 Attack.<br/>Whenever your General destroys an enemy, restore 2 Health to your General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20201,
    'name': 'Sphere of Darkness',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': "Turn an enemy minion's space into <b>Shadow Creep</b>. Draw a card.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30030,
    'name': 'The Releaser',
    'expansion': 'ancients',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      'When this artifact breaks, summon a random friendly non-token minion destroyed this game nearby.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20367,
    'name': 'Yielding Depths',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': 'If you have three or more <b>Shadow Creep</b>, draw 2 cards.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20348,
    'name': 'Abhorrent Unbirth',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      'Destroy all friendly minions to summon a 1/1 Abomination that gains their Attack, Health, and keywords.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 328,
    'name': 'Blood Baronette',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': "Opening Gambit: Double a nearby Wraithling's Attack and Health.",
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20257,
    'name': 'Blood Echoes',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      'Destroy all friendly minions and resummon them on random spaces at end of turn.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 361,
    'name': 'Bonecrusher',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': '<b>Intensify</b>: This minion gains +5 Attack.',
    'attack': 0,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 344,
    'name': 'Bound Tormentor',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      '<b>Sentinel</b>: Minion summoned.<br/>Put a copy of the minion that transformed this into your action bar. It costs 2 less.',
    'attack': 2,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 362,
    'name': 'Chittering Tiller',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      '<b>Frenzy</b><br/><b>Opening Gambit</b>: Teleport the enemy General one space forward.',
    'attack': 4,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20133,
    'name': 'Deathfire Crescendo',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text': 'Give a friendly minion, "<b>Deathwatch</b>: Gains +2/+2."',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20340,
    'name': 'Horrific Visage',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': 'Give all enemy minions -4 Attack until your next turn.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 334,
    'name': 'Horror Burster',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      '<b>Dying Wish</b>: Transform a random friendly minion into a 6/6 Horror.',
    'attack': 4,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20321,
    'name': 'Infest',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      'Choose an enemy minion. When it dies, give this effect to all nearby enemy minions and deal 2 damage to the enemy General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30034,
    'name': 'Mindlathe',
    'expansion': 'unearthed',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      'After your General damages a minion, reactivate and take control of it until the end of your turn.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20374,
    'name': 'Munch',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      'Steal Health from an enemy minion for each friendly Shadow Creep (but not more than its Health).',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 319,
    'name': 'Nightsorrow Assassin',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      '<b>Opening Gambit</b>: Destroy a nearby enemy minion with 2 or less attack.',
    'attack': 2,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20057,
    'name': 'Ritual Banishing',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': 'Destroy a friendly minion to destroy an enemy minion.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20065,
    'name': 'Shadow Reflection',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': 'Give a friendly minion +5 Attack.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 311,
    'name': 'Shadow Watcher',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text': '<b>Deathwatch</b>: Gains +1/+1.',
    'attack': 2,
    'health': 2,
    'spirit': 0
  },
  {
    'cardid': 343,
    'name': 'Skullprophet',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      '<b>Sentinel</b>: General attacks.<br/>The enemy General has -1 Attack.',
    'attack': 2,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 30002,
    'name': 'Soul Grimwar',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text': 'Your General gains, "<b>Deathwatch</b>: Gains +2 Attack."',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20205,
    'name': 'Void Steal',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      'Give an enemy minion -3 Attack. Nearby friendly minions gain +3 Attack.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 350,
    'name': 'Void Talon',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': '<b>Build</b>: (1).',
    'attack': 6,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20089,
    'name': 'Wraithling Fury',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Give a friendly Wraithling minion +4/+4.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20072,
    'name': 'Wraithling Swarm',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text': 'Summon three 1/1 Wraithlings nearby each other.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 345,
    'name': 'Xerroloth',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      '<b>Sentinel</b>: Spell cast.<br/>Whenever your opponent casts a spell, put a 4/4 Fiend into your action bar.',
    'attack': 3,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 309,
    'name': 'Abyssal Juggernaut',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': 'This minion has +1/+1 for each friendly <b>Shadow Creep</b>.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 310,
    'name': 'Bloodtide Priestess',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': '<b>Deathwatch</b>: Summon a Wraithling on a random nearby space.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20131,
    'name': 'Breath Of The Unborn',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      'Deal 2 damage to all enemy minions. Fully heal all friendly minions.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 348,
    'name': 'Cacophynos',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': '<b>Dying Wish</b>: Destroy a random nearby enemy minion.',
    'attack': 6,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20069,
    'name': 'Dark Seed',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      "Deal 1 damage to the enemy General for each card in the opponent's action bar.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 312,
    'name': 'Deepfire Devourer',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      '<b>Frenzy</b><br/><b>Opening Gambit</b>: Destroy friendly minions around it and gain +2/+2 for each minion.',
    'attack': 4,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 341,
    'name': 'Desolator',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Opening Gambit</b>: Steal 2 Health from the enemy General.<br/><b>Dying Wish</b>: Return Desolator to your action bar.',
    'attack': 2,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 353,
    'name': 'Gate to the Undervault',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': 'Structure',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Build</b>: (3).<br/><b>Invulnerable</b><br/><b>Deathwatch</b>: Summon a random Demon nearby.',
    'attack': 0,
    'health': 0,
    'spirit': None
  },
  {
    'cardid': 30020,
    'name': 'Ghost Azalea',
    'expansion': 'shimzar',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text': 'Your General gains +1 Attack for each friendly <b>Shadow Creep</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 340,
    'name': 'Nekomata',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      '<b>Dying Wish</b>: Draw two minions with <b>Dying Wish</b> from your deck.',
    'attack': 4,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 336,
    'name': 'Nightshroud',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Arcanyst',
    'cost': 4,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      '<b>Bond</b>: Your General steals 1 Health from the enemy General for each other friendly Arcanyst.',
    'attack': 5,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20051,
    'name': 'Shadow Nova',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text': 'Turn a 2x2 area into <b>Shadow Creep</b>.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 324,
    'name': 'Shadow Sister Kelaino',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text': 'Whenever an enemy takes damage, restore 1 Health to your General.',
    'attack': 3,
    'health': 3,
    'spirit': 0
  },
  {
    'cardid': 20334,
    'name': 'Vellumscry',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'abyssian',
    'text': 'Destroy a friendly minion to draw three cards.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30051,
    'name': 'Wraithcrown',
    'expansion': 'mythron',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Friendly Wraithlings have +2/+2.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 321,
    'name': 'Black Solus',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'When you summon a Wraithling, this minion gains +2 Attack.',
    'attack': 4,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 20284,
    'name': 'Corporeal Cadence',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Destroy a friendly minion to deal its Attack to the enemy General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20061,
    'name': 'Dark Transformation',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'basic',
    'faction': 'abyssian',
    'text': 'Destroy an enemy minion and summon a 1/1 Wraithling on that space.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 30039,
    'name': 'Furor Chakram',
    'expansion': 'immortal',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 5,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text': 'Friendly minions gain +2 Attack and <b>Frenzy</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 358,
    'name': 'Hexclaw',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Dying Wish</b>: The enemy General gains, "At the start of your turn, take 1 damage."',
    'attack': 7,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 20050,
    'name': 'Nether Summoning',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      'Summon 2 non-token minions destroyed since the end of your last turn nearby.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 325,
    'name': 'Night Fiend',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'common',
    'faction': 'abyssian',
    'text':
      '<b>Opening Gambit</b>: Deal 2 damage to each enemy on or near friendly <b>Shadow Creep</b>.',
    'attack': 4,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 322,
    'name': 'Reaper of the Nine Moons',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      "<b>Flying</b><br/><b>Dying Wish</b>: Summon a random minion from the opponent's deck on this space.",
    'attack': 5,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 318,
    'name': 'Shadowdancer',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'rare',
    'faction': 'abyssian',
    'text':
      '<b>Deathwatch</b>: Deal 1 damage to the enemy General, and restore 1 Health to your General.',
    'attack': 4,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 360,
    'name': 'Abyssal Tormentor',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Provoke</b><br/>Your <b>Shadow Creep</b> deals damage equal to the number of friendly <b>Shadow Creep</b>.',
    'attack': 6,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 20331,
    'name': 'Betrayal',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Enemy minions nearby their General attack their General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 330,
    'name': 'Klaxon',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Provoke</b><br/><b>Dying Wish</b>: Turn six random spaces into <b>Shadow Creep</b>.',
    'attack': 6,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 352,
    'name': 'Moonrider',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': '<b>Blood Surge</b>: Summon a 4/4 Fiend on a nearby space.',
    'attack': 6,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 20227,
    'name': 'Necrotic Sphere',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      'Destroy ALL minions nearby your General and summon Wraithlings in their place.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20154,
    'name': 'Rite Of The Undervault',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': 'Draw to fill your action bar.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20373,
    'name': 'Unfathomable Rite',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text': "Draw cards from your opponent's deck to fill your action bar.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 314,
    'name': 'Vorpal Reaver',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Celerity</b><br/><b>Dying Wish</b>: Summon six Wraithlings on random spaces.',
    'attack': 6,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 329,
    'name': 'Arcane Devourer',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 7,
    'rarity': 'epic',
    'faction': 'abyssian',
    'text':
      '<b>Opening Gambit</b>: The next minion you summon this turn costs 1.',
    'attack': 8,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 347,
    'name': 'Stygian Observer',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 7,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text': '<b>Deathwatch</b>: Give minions in your action bar +2/+2.',
    'attack': 7,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 338,
    'name': 'Death Knell',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Arcanyst',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Opening Gambit</b>: Summon all friendly non-token Arcanysts destroyed this game nearby.',
    'attack': 6,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 333,
    'name': 'Grandmaster Variax',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Opening Gambit</b>: Your Bloodbound Spell costs 3 and is now AWESOME.',
    'attack': 8,
    'health': 8,
    'spirit': None
  },
  {
    'cardid': 20213,
    'name': 'Obliterate',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      'Destroy all friendly <b>Shadow Creep</b> to deal that much damage to all enemies.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 320,
    'name': 'Spectral Revenant',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      '<b>Rush</b><br/>Whenever this damages an enemy minion, deal 4 damage to the enemy General.',
    'attack': 6,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 20380,
    'name': 'Unleash the Evil',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text':
      'Summon a copy of the minion your opponent most recently summoned from their action bar. It gains <b>Rush</b> and <b>Flying</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20264,
    'name': 'Doom',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 9,
    'rarity': 'legendary',
    'faction': 'abyssian',
    'text': 'The enemy General is DOOMED and will die after three turns.',
    'attack': None,
    'health': None,
    'spirit': None
  }
]

with open('abyssian.csv', 'w', newline='') as csvfile:
	w = csv.writer(csvfile)
	for d in cards:
		w.writerow([d['cardid']])
