import csv

cards = [
  {
    'cardid': 20111,
    'name': 'Dampening Wave',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 0,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': 'Choose an enemy minion. It can no longer counterattack.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 20112,
    'name': 'Flash Reincarnation',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 0,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      'If the next card you play this turn is a minion, it costs 2 less and takes 2 damage.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20119,
    'name': 'Amplification',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'magmar',
    'text': 'Give a friendly damaged minion +2 Attack and +4 Health.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20115,
    'name': 'Dance of Dreams',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': 'Whenever a friendly minion dies this turn, draw a card.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 30037,
    'name': 'Eternal Heart',
    'expansion': 'unearthed',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 1,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': 'Your General cannot die.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30028,
    'name': 'Godhammer',
    'expansion': 'ancients',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 1,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'Your minions have "Grow: +1/+1."',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20116,
    'name': 'Greater Fortitude',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': 'Give a friendly minion +2/+2.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 20203,
    'name': 'Lava Lance',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      'Deal 2 damage to a minion. If you have an Egg, deal 4 damage instead.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30049,
    'name': 'Rage Reactor',
    'expansion': 'immortal',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 1,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      'Your General gains +1 Attack.<br/>Whenever your General destroys an enemy, summon a Ripper Egg on that space.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20202,
    'name': 'Razor Skin',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      'Give all friendly minions +1 Attack. Put a random Battle Pet into your action bar.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 421,
    'name': 'Rex',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Battle Pet',
    'cost': 1,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Rebirth</b>',
    'attack': 3,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20114,
    'name': 'Tremor',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Stun</b> enemy minions in a 2x2 area.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 451,
    'name': 'Angered Okkadok',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Intensify</b>: This minion gains +1/+1.',
    'attack': 1,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 444,
    'name': 'Biomimetic Hulk',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Build</b>: (3).',
    'attack': 10,
    'health': 10,
    'spirit': None
  },
  {
    'cardid': 20258,
    'name': 'Cascading Rebirth',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      'Destroy a friendly minion to summon a random Magmar minion that costs 1 more.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20369,
    'name': 'Deep Impact',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'Deal damage to a minion to reduce its Health to 1.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20113,
    'name': 'Diretide Frenzy',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': 'Give a friendly minion +1 Attack and <b>Frenzy</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20312,
    'name': 'Embryotic Insight',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': 'If you have an Egg, draw 2 cards.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20225,
    'name': 'Entropic Gaze',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': 'Deal 2 damage to the enemy General. Both players draw a card.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 420,
    'name': 'Gro',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Battle Pet',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': '<b>Grow</b>: +1/+1',
    'attack': 2,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20358,
    'name': 'Invigoration',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Intensify</b>: Restore 3 Health to your General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30013,
    'name': 'Iridium Scale',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Your General gains <b>Frenzy</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 409,
    'name': 'Kujata',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'magmar',
    'text':
      'Your minions cost 1 less to summon and take 1 damage when summoned from your action bar.',
    'attack': 2,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 20382,
    'name': 'Mitotic Induction',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'magmar',
    'text':
      'Summon an Egg of the minion most recently summoned from your action bar.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20125,
    'name': 'Natural Selection',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'magmar',
    'text':
      'Destroy ANY minion with the lowest Attack or tied for the lowest Attack.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 406,
    'name': 'Phalanxar',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': '',
    'attack': 6,
    'health': 1,
    'spirit': 0
  },
  {
    'cardid': 20268,
    'name': 'Primal Ballast',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'Dispel a space. If there is a minion on that space, give it +2/+2.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 430,
    'name': 'Rancour',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      'Whenever your General takes damage, this minion gains that much attack. ',
    'attack': 1,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 446,
    'name': 'Seismoid',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': 'Mech',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      'Whenever you summon a Mech minion from your action bar, both players draw a card.',
    'attack': 3,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20288,
    'name': "Vaath's Brutality",
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Stun</b> an enemy minion. Give your General +1 Attack.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 438,
    'name': 'Warpup',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': '<b>Forcefield</b>, <b>Frenzy</b>',
    'attack': 1,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 412,
    'name': 'Young Silithar',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Rebirth</b>',
    'attack': 2,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 30055,
    'name': 'Zoetic Charm',
    'expansion': 'mythron',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Your General has +1 Attack.<br/>Your Eggs have <b>Forcefield</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20390,
    'name': 'Bellow',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      'Give a friendly minion +3 Attack.<br/><b>Stun</b> enemy minions around it.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 439,
    'name': 'Catalyst Quillbeast',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text': 'Whenever you cast a spell, deal 1 damage to ALL minions.',
    'attack': 3,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 402,
    'name': 'Earth Walker',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': '<b>Grow</b>: +1/+1',
    'attack': 3,
    'health': 3,
    'spirit': 0
  },
  {
    'cardid': 20346,
    'name': 'Effulgent Infusion',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text': "Give a friendly minion +Attack equal to your General's Attack.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20291,
    'name': 'Endure the Beastlands',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Turn a 2x2 area into <b>Primal Flourish</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 448,
    'name': 'Erratic Raptyr',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      '<b>Rebirth</b><br/>After this minion attacks or counterattacks, turn it into an Egg.',
    'attack': 5,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 20162,
    'name': 'Kinetic Equilibrium',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      'Deal 2 damage to ALL minions in a 3x3 area. Friendly minions in the area also gain +2 Attack.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 455,
    'name': 'Krater',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      '<b>Opening Gambit</b>: Deal 1 damage to everything (including itself).',
    'attack': 2,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 423,
    'name': 'Moloki Huntress',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'magmar',
    'text':
      "<b>Grow</b>: +1/+1<br/>Friendly minions grow at the start of BOTH player's turns.",
    'attack': 1,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 454,
    'name': 'Oropsisaur',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      '<b>Grow</b>: +1/+1.<br/>Whenever another friendly minion with <b>Grow</b> survives damage, that minion grows.',
    'attack': 2,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 410,
    'name': 'Primordial Gazer',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': '<b>Opening Gambit</b>: Give a nearby friendly minion +2/+2.',
    'attack': 2,
    'health': 2,
    'spirit': 0
  },
  {
    'cardid': 432,
    'name': 'Ragebinder',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Golem',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Rebirth</b><br/><b>Bond</b>: Restore 3 Health to your General.',
    'attack': 3,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20234,
    'name': 'Tectonic Spikes',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'Both players draw 3 cards. Deal 3 damage to both Generals.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 437,
    'name': 'Terradon',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '',
    'attack': 2,
    'health': 8,
    'spirit': None
  },
  {
    'cardid': 429,
    'name': 'Thraex',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      '<b>Blood Surge</b>: All friendly minions gain +1 Attack (including itself).',
    'attack': 2,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 30017,
    'name': 'Twin Fang',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      'Whenever a friendly minion or your General takes damage, your General gains +2 Attack.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20338,
    'name': 'Upper Hand',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      "Deal 1 damage to an enemy minion for each card in your opponent's action bar.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20296,
    'name': 'Verdant Fulmination',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'magmar',
    'text':
      "Your minions on friendly <b>Primal Flourish</b> grow. Turn your other minions' spaces into <b>Primal Flourish</b>.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 417,
    'name': 'Vindicator',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': 'Whenever your opponent draws a card, this minion gains +2/+2.',
    'attack': 1,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 30012,
    'name': 'Adamantite Claws',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 4,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': 'Your General gains +4 Attack.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 453,
    'name': 'Beastclad Hunter',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'Takes no damage from minions with less Attack.',
    'attack': 3,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 20297,
    'name': 'Blood Rage',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'magmar',
    'text':
      'Give a friendly minion +1/+1 for each time damage was dealt this turn.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 428,
    'name': 'Drogon',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': "<b>Blood Surge</b>: Double your General's Attack this turn.",
    'attack': 5,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 419,
    'name': 'Earth Sister Taygete',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      'Whenever this minion takes damage, deal that much damage to all nearby enemies.',
    'attack': 3,
    'health': 4,
    'spirit': 0
  },
  {
    'cardid': 20117,
    'name': 'Earth Sphere',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'magmar',
    'text': 'Restore 8 Health to your General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20157,
    'name': 'Egg Morph',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'Turn a non-Egg minion into an Egg, or hatch an Egg.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 407,
    'name': 'Elucidator',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      '<b>Rush</b><br/><b>Opening Gambit</b>: Deal 4 damage to your General.',
    'attack': 5,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20370,
    'name': 'Gargantuan Growth',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'Give a minion, "Grow: +8/+8."',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 445,
    'name': 'Gigaloth',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      '<b>Build</b>: (2).<br/>Whenever this minion attacks, other friendly minions gain +3/+3.',
    'attack': 7,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 403,
    'name': 'Grimrock',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Grow</b>: +2/+2',
    'attack': 3,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 458,
    'name': 'Haruspex',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': 'Whenever this minion takes damage, your opponent draws a card.',
    'attack': 7,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 20344,
    'name': 'Homeostatic Rebuke',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'ALL minions attack themselves.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20156,
    'name': 'Mind Steal',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': "Steal a random minion from your opponent's deck and summon it.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 440,
    'name': 'Omniseer',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      '<b>Opening Gambit</b>: Turn a nearby space into <b>Primal Flourish</b>.',
    'attack': 4,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 441,
    'name': 'Progenitor',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      '<b>Opening Gambit</b>: Each of your other non-Egg minions summon an Egg of itself behind itself.',
    'attack': 5,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20319,
    'name': 'Pupabomb',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Destroy a friendly Egg to deal 4 damage to enemies around it.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 435,
    'name': 'Rizen',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'magmar',
    'text':
      'Whenever your opponent summons a minion, this minion summons an Egg of itself nearby.',
    'attack': 3,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 20218,
    'name': 'Thumping Wave',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      'Give a minion +5 Attack. At end of turn, transform it into a 3/3 Kin.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20245,
    'name': "Valknu's Seal",
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Summon an Egg that hatches into a copy of your General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 413,
    'name': 'Veteran Silithar',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Rebirth</b>',
    'attack': 4,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 422,
    'name': 'Wild Inceptor',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Opening Gambit</b>: Hatch a friendly Egg.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 404,
    'name': 'Kolossus',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'common',
    'faction': 'magmar',
    'text': '<b>Grow</b>: +4/+4',
    'attack': 1,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 433,
    'name': 'Lavaslasher',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Golem',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': '<b>Opening Gambit</b>: This minion fights a nearby enemy minion.',
    'attack': 4,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 452,
    'name': 'Mortar-maw',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'magmar',
    'text':
      '<b>Ranged</b><br/>Whenever this minion attacks, it also damages enemies around its target.',
    'attack': 4,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20206,
    'name': "Nature's Confluence",
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Summon four copies of a random Battle Pet in a 2x2 area.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20122,
    'name': 'Plasma Storm',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'basic',
    'faction': 'magmar',
    'text': 'Destroy ALL minions with 3 or less Attack.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 415,
    'name': 'Spirit Harvester',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'rare',
    'faction': 'magmar',
    'text': 'At the end of your turn, deal 1 damage to ALL other minions.',
    'attack': 5,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 426,
    'name': 'Visionar',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Whenever ANY player draws a card, this minion gains +1/+1.',
    'attack': 5,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 447,
    'name': 'Armada',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': '<b>Blood Surge</b>: Deal 5 damage to the closest enemy.',
    'attack': 5,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 20124,
    'name': 'Chrysalis Burst',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': 'Summon a random Egg in 4 random spaces.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 424,
    'name': 'Dreadnought',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': '<b>Rebirth</b><br/>Egg minions you summon gain +2/+2.',
    'attack': 4,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 20063,
    'name': 'Fractal Replication',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Summon two copies of a friendly minion nearby that minion.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 405,
    'name': 'Makantor Warbeast',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': '<b>Frenzy</b><br/><b>Rush</b>',
    'attack': 4,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20121,
    'name': 'Metamorphosis',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      "Transform all enemy minions into 1/1 Magma with no abilities until the end of your opponent's turn.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30025,
    'name': 'Morin-Khur',
    'expansion': 'shimzar',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      'Your General gains +3 Attack. Whenever your General deals damage, hatch all friendly Eggs.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20118,
    'name': 'Bounded Lifeforce',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 7,
    'rarity': 'epic',
    'faction': 'magmar',
    'text': 'Your General becomes 10/10.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20292,
    'name': 'Evolutionary Apex',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 7,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      'BOTH players put all minions in their action bars onto the battlefield nearby their General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 414,
    'name': 'Silithar Elder',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 7,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      '<b>Rebirth</b><br/>At the end of your turn, summon a Silithar Elder Egg nearby.',
    'attack': 7,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 408,
    'name': 'Unstable Leviathan',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 7,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      'At the start of your turn, deal 4 damage to a random minion or General.',
    'attack': 11,
    'health': 11,
    'spirit': None
  },
  {
    'cardid': 20383,
    'name': 'Extinction Event',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': 'Each of your Eggs hatches into a Katastrophosaurus.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20219,
    'name': 'Flaming Stampede',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text': 'Deal 8 damage to ALL non-Egg minions and Generals.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 434,
    'name': 'Juggernaut',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Golem',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      '<b>Grow</b>: +5/+5<br/>Whenever this minion takes damage, summon that many random Golem Eggs nearby.',
    'attack': 4,
    'health': 10,
    'spirit': None
  },
  {
    'cardid': 20339,
    'name': 'Saurian Finality',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      '<b>Stun</b> the enemy General.<br/>Your General gains +3 Attack.<br/>Both players lose 3 mana.<br/>Restore 10 Health to your General.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 436,
    'name': 'Grandmaster Kraigon',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 9,
    'rarity': 'legendary',
    'faction': 'magmar',
    'text':
      '<b>Forcefield</b>, <b>Frenzy</b>, <b>Grow</b>: +7/+7.<br/>Your General has:<br/><b>Forcefield</b>, <b>Frenzy</b>, <b>Grow</b>: +7/+7.',
    'attack': 7,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 425,
    'name': 'Mandrake',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 12,
    'rarity': 'rare',
    'faction': 'magmar',
    'text':
      "Costs 1 less for each minion summoned from ANY player's action bar this game.",
    'attack': 6,
    'health': 6,
    'spirit': None
  }
]

with open('magmar.csv', 'w', newline='') as csvfile:
	w = csv.writer(csvfile)
	for d in cards:
		w.writerow([d['cardid']])
