import csv

cards = [
  {
    'cardid': 20329,
    'name': 'Essence Sculpt',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 0,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      'Choose a <b>Stunned</b> minion. Put a copy of that card into your action bar.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20139,
    'name': 'Flash Freeze',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 0,
    'rarity': 'basic',
    'faction': 'vanar',
    'text': 'Deal 1 damage to a minion and <b>Stun</b> it.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 20150,
    'name': 'Polarity',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 0,
    'rarity': 'common',
    'faction': 'vanar',
    'text': "Switch ANY minion's Attack and Health.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20393,
    'name': 'Aspect of Ego',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'Transform ANY minion into a random minion of the same cost.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30031,
    'name': 'Iceshatter Gauntlet',
    'expansion': 'ancients',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 1,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      'Whenever your General attacks a <b>Stunned</b> minion, destroy it instantly.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20138,
    'name': 'Mesmerize',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'Teleport an enemy one space.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 510,
    'name': 'Snow Chaser',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 1,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      '<b>Infiltrate</b>:  When this minion dies, return it to your action bar.',
    'attack': 2,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 30035,
    'name': 'The Dredger',
    'expansion': 'unearthed',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 1,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      'Whenever your General damages an enemy, randomly teleport them to your starting side of the battlefield.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20209,
    'name': 'Vespyric Call',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      'Put a random Vespyr minion into your action bar. It costs 1 less and has +1/+1.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20375,
    'name': 'Wanderlust',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 1,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      '<b>Intensify</b>: Teleport 1 random enemy minion to a space on your starting side of the battlefield.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20324,
    'name': 'Aspect of the Bear',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      'Transform ANY minion into a 4/5 Ursaplomb that will not counterattack.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20144,
    'name': 'Aspect of the Ravager',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'vanar',
    'text': 'Transform ANY minion into a 3/3 Ravager with no abilities.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 20149,
    'name': 'Bonechill Barrier',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      'Summon three joined 0/2 Vespyr Walls.  Minions that attack these walls are <b>Stunned</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 512,
    'name': 'Borean Bear',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'Whenever you summon a Vespyr minion, this minion gains +1 Attack.',
    'attack': 1,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20137,
    'name': 'Boundless Courage',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': 'Give a friendly minion +2 Attack. It takes no damage this turn.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 531,
    'name': 'Bur',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Battle Pet',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      'When this minion survives damage, transform it into a different Battle Pet.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20134,
    'name': 'Chromatic Cold',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'vanar',
    'text':
      'Dispel a space. If there is an enemy on that space, deal it 1 damage.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 540,
    'name': 'Circulus',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Arcanyst',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': 'Whenever you cast a spell, add a 2/1 Illusion to your action bar.',
    'attack': 1,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 30016,
    'name': 'Coldbiter',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 2,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      'At the end of your turn, your General deals 2 damage to each enemy minion around them.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20228,
    'name': 'Concealing Shroud',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'Your General takes no damage until your next turn.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 555,
    'name': 'Cryoblade',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'Deals double damage to <b>Stunned</b> enemies.',
    'attack': 2,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 550,
    'name': 'Crystal Arbiter',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': "This minion has +3 Attack on your opponent's turn.",
    'attack': 1,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 505,
    'name': 'Crystal Cloaker',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'vanar',
    'text': '<b>Infiltrate</b>: Gain +2 Attack.',
    'attack': 2,
    'health': 3,
    'spirit': 0
  },
  {
    'cardid': 506,
    'name': 'Crystal Wisp',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Dying Wish</b>: Permanently gain 1 mana crystal.',
    'attack': 1,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20237,
    'name': 'Frigid Corona',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Stun</b> an enemy minion. Draw a card.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20135,
    'name': 'Frostfire',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'basic',
    'faction': 'vanar',
    'text':
      'Give a friendly minion +3 Attack. If it is Vespyr, also give it +3 Health.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 20147,
    'name': 'Gravity Well',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'Summon four joined 0/1 Walls with <b>Provoke</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20160,
    'name': 'Hailstone Prison',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'Return ANY minion to its action bar.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 517,
    'name': 'Hearth-Sister',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Opening Gambit</b>: Switch positions with ANY other minion.',
    'attack': 3,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 530,
    'name': 'Icy',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Battle Pet',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Opening Gambit</b>: <b>Stun</b> a nearby enemy.',
    'attack': 2,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20211,
    'name': 'Lightning Blitz',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      "Give all friendly minions +1/+1 and randomly teleport them to your opponent's starting side of the battlefield.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20261,
    'name': 'Mana Deathgrip',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      'Deal 1 damage to an enemy minion. If it dies this turn, permanently gain 1 mana crystal.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20140,
    'name': 'Mark of Solitude',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'One minion becomes 5/5. It can no longer attack Generals.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 554,
    'name': 'Protosensor',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Build</b>: (1).<br/><b>Airdrop</b>',
    'attack': 2,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 30056,
    'name': 'Resonance Scythe',
    'expansion': 'mythron',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      'Your General has +1 Attack.<br/>Reactivate your General whenever they destroy a <b>Stunned</b> enemy.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20337,
    'name': 'Shatter',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'Destroy a <b>Stunned</b> enemy minion.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 545,
    'name': 'Shivers',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 2,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      '<b>Flying</b><br/><b>Infiltrate</b>: When this minion attacks, permanently gain 1 mana crystal.',
    'attack': 2,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 567,
    'name': 'Thicket Augur',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 2,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Intensify</b>: Summon 1 Treant with <b>Provoke</b> nearby.',
    'attack': 1,
    'health': 1,
    'spirit': None
  },
  {
    'cardid': 20214,
    'name': "Aspect of Shim'Zar",
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'Transform ANY minion into a random Battle Pet.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20148,
    'name': 'Blazing Spines',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'Summon two joined 3/3 Walls that can attack.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20371,
    'name': 'Cryonic Potential',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'Give an exhausted friendly minion +6/+6.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20347,
    'name': 'Crystalline Reinforcement',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': 'Double the Attack and Health buffs of friendly minions.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 565,
    'name': 'Disciple of Yggdra',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      "When an enemy is <b>Stunned</b>, transform this minion into Yggdra's Voracity.",
    'attack': 2,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 548,
    'name': 'Drake Dowager',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      '<b>Sentinel</b>: General attacks.<br/><b>Ranged</b><br/>Whenever this attacks, summon a 4/4 Flying Drake nearby.',
    'attack': 1,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 503,
    'name': 'Fenrir Warmaster',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'basic',
    'faction': 'vanar',
    'text': '<b>Dying Wish</b>: Summon a 3/2 Ghost Wolf on this space.',
    'attack': 3,
    'health': 2,
    'spirit': 0
  },
  {
    'cardid': 547,
    'name': 'Freeblade',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      '<b>Sentinel</b>: Minion summoned.<br/>This switches positions with the minion that transformed it.',
    'attack': 3,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 519,
    'name': 'Glacial Elemental',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      'Whenever you summon a Vespyr minion, deal 2 damage to a random enemy minion.',
    'attack': 2,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20266,
    'name': 'Glacial Fissure',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': 'Deal 8 damage to EVERYTHING in the center column.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 533,
    'name': 'Iceblade Dryad',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      '<b>Opening Gambit</b>: Give a friendly Vespyr minion +1/+1 and <b>Flying</b>.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 539,
    'name': 'Kindred Hunter',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Arcanyst',
    'cost': 3,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Bond</b>: Summon a 3/3 Night Howler on a random nearby space.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 549,
    'name': 'Moonlit Basilysk',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      '<b>Sentinel</b>: Spell cast.<br/>Whenever your opponent casts a spell, this minion gains +3/+3.',
    'attack': 2,
    'health': 2,
    'spirit': None
  },
  {
    'cardid': 536,
    'name': 'Myriad',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 3,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Blood Surge</b>: Summon a random Wall nearby.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 20394,
    'name': 'Permafrost',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 3,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      '<b>Stun</b> an enemy minion.<br/><b><b>Stun</b>ned</b> enemy minions <b>Stun</b> a nearby enemy.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 529,
    'name': 'Snow Rippler',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 3,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      '<b>Infiltrate</b>: Whenever this minion damages a General, put a random Battle Pet into your action bar.',
    'attack': 3,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 30015,
    'name': 'Snowpiercer',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 3,
    'rarity': 'basic',
    'faction': 'vanar',
    'text': 'Your General gains +3 Attack.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 511,
    'name': 'Wolfraven',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 3,
    'rarity': 'common',
    'faction': 'vanar',
    'text': '<b>Flying</b><br/><b>Infiltrate</b>: Gain +3 Attack.',
    'attack': 1,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20145,
    'name': 'Aspect of the Wyrm',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      'Transform ANY minion into a 4/4 Whyte Drake with <b>Flying</b>. Nearby friendly minions gain <b>Flying</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20136,
    'name': 'Avalanche',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'basic',
    'faction': 'vanar',
    'text':
      'Deal 4 damage to everything on your starting side of the battlefield and <b>Stun</b> them.',
    'attack': None,
    'health': None,
    'spirit': 0
  },
  {
    'cardid': 20298,
    'name': 'Blinding Snowstorm',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      'Deal 1 damage to all enemies. Those enemies can only move 1 space next turn.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20165,
    'name': 'Cryogenesis',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      'Deal 4 damage to an enemy minion. Draw a Vespyr minion from your deck.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 557,
    'name': 'Denadoro',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'Your minions are always infiltrated.',
    'attack': 4,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 20391,
    'name': 'Endless Hunt',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      'Summon a 3/3 Vespyr Night Howler.<br/>Put an Endless Hunt into your action bar.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 542,
    'name': 'Hydrogarm',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      '<b>Blood Surge</b>: Deal 1 damage to enemy minions in this row and <b>Stun</b> them.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 561,
    'name': 'Malicious Wisp',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      '<b>Opening Gambit</b>: Take a mana crystal from your opponent.<br/><b>Dying Wish</b>: Give back the mana crystal.',
    'attack': 4,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 563,
    'name': 'Meltwater Moose',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 4,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'When this minion is summoned, <b>Stun</b> it.',
    'attack': 6,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 513,
    'name': 'Razorback',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      '<b>Opening Gambit</b>: Give all friendly minions +2 Attack this turn.',
    'attack': 4,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 537,
    'name': 'Sleet Dasher',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'Whenever this minion destroys an enemy, reactivate it.',
    'attack': 3,
    'health': 6,
    'spirit': None
  },
  {
    'cardid': 515,
    'name': 'Voice of the Wind',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      'Whenever you summon a minion from your action bar, summon a 2/2 Vespyr Winter Maerid nearby.',
    'attack': 4,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20208,
    'name': 'Wailing Overdrive',
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'common',
    'faction': 'vanar',
    'text':
      "Give a friendly minion on your opponent's starting side of the battlefield +5/+5.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30021,
    'name': 'White Asp',
    'expansion': 'shimzar',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      'Your General gains +3 Attack. Whenever your General destroys a minion, summon a 3/3 Blazing Spine Wall on that space.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 528,
    'name': 'Wind Sister Maia',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 4,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'Friendly minions with <b>Infiltrate</b> have +1/+1.',
    'attack': 4,
    'health': 5,
    'spirit': 0
  },
  {
    'cardid': 30019,
    'name': 'Winterblade',
    'expansion': 'core',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      'Your General gains +2 Attack. Enemy minions damaged by your General are <b>Stunned</b>.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20330,
    'name': 'Wintertide',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 4,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': 'Summon three 2/2 Vespyr Winter Maerids on any column.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 30040,
    'name': 'Animus Plate',
    'expansion': 'immortal',
    'cardtype': 'artifact',
    'tribe': '',
    'cost': 5,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      'Your General gains +2 Attack.<br/>Whenever your General attacks or counterattacks, give all friendly Vespyr minions +2/+2.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 526,
    'name': 'Arctic Displacer',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 5,
    'rarity': 'basic',
    'faction': 'vanar',
    'text': '<b>Airdrop</b>',
    'attack': 10,
    'health': 4,
    'spirit': 0
  },
  {
    'cardid': 20343,
    'name': 'Auroraboros',
    'expansion': 'immortal',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      'Give friendly minions "<b>Dying Wish</b>: Re-summon this minion on this space."',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 560,
    'name': 'Cloudcaller',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      '<b>Opening Gambit</b>: Your Bloodbound Spell refreshes and is Lesser Waterball this turn.',
    'attack': 4,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 20229,
    'name': 'Enfeeble',
    'expansion': 'ancients',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': 'All minions become 1/1.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 562,
    'name': 'Fenrir Berserker',
    'expansion': 'mythron',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': '<b>Dying Wish</b>: Summon a Fenrir Warmaster on this space.',
    'attack': 4,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 507,
    'name': 'Frosthorn Rhyno',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': '<b>Infiltrate</b>: Gain +1 Attack and <b>Celerity</b>.',
    'attack': 6,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 534,
    'name': 'Frostiva',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      '<b>Forcefield</b><br/>Whenever this minion attacks or is attacked, summon a 3/3 Vespyr Night Howler nearby.',
    'attack': 3,
    'health': 3,
    'spirit': None
  },
  {
    'cardid': 532,
    'name': 'Huldra',
    'expansion': 'shimzar',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 5,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      '<b>Opening Gambit</b>: Give a friendly Vespyr minion <b>Celerity</b>.',
    'attack': 3,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20276,
    'name': 'Luminous Charge',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'rare',
    'faction': 'vanar',
    'text':
      'Summon five joined 0/1 Walls that deal 2 damage to nearby enemies when destroyed.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20163,
    'name': 'Spirit of the Wild',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      "Reactivate friendly minions on your opponent's starting side of the battlefield.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20289,
    'name': 'Vespyrian Might',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 5,
    'rarity': 'common',
    'faction': 'vanar',
    'text': 'Give a Vespyr minion +2/+2 for each friendly Vespyr.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20146,
    'name': 'Aspect of the Mountains',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      'Transform ANY minion into a 5/5 Seismic Elemental. Deal 5 damage to enemy minions around it.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 556,
    'name': 'Draugar Eyolith',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 6,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      '<b>Build</b>: (2).<br/>While this is building or on the battlefield, enemy minions and Generals can only move 1 space.',
    'attack': 7,
    'health': 14,
    'spirit': None
  },
  {
    'cardid': 508,
    'name': 'Draugar Lord',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'vanar',
    'text': '<b>Dying Wish</b>: Summon a 4/8 Ice Drake on this space.',
    'attack': 4,
    'health': 8,
    'spirit': None
  },
  {
    'cardid': 552,
    'name': 'Echo Deliverant',
    'expansion': 'immortal',
    'cardtype': 'minion',
    'tribe': 'Mech',
    'cost': 6,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'Whenever you summon another Mech, summon a copy of it nearby.',
    'attack': 6,
    'health': 4,
    'spirit': None
  },
  {
    'cardid': 20207,
    'name': 'Frostburn',
    'expansion': 'core',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'rare',
    'faction': 'vanar',
    'text': 'Deal 3 damage to all enemy minions.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 20295,
    'name': 'Icebreak Ambush',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 6,
    'rarity': 'epic',
    'faction': 'vanar',
    'text':
      "Summon an ambush of <b>Infiltrate</b> minions on your opponent's starting side of the battlefield.",
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 514,
    'name': 'Ancient Grove',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': 'Vespyr',
    'cost': 7,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      '<b>Provoke</b><br/><b>Opening Gambit</b>: Your minions gain "<b>Dying Wish</b>: Summon a 1/1 Treant with <b>Provoke</b>".',
    'attack': 7,
    'health': 7,
    'spirit': None
  },
  {
    'cardid': 20293,
    'name': 'Flawless Reflection',
    'expansion': 'unearthed',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 7,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'Choose a minion. Transform ALL nearby minions into copies of it.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 541,
    'name': 'Ghost Seraphim',
    'expansion': 'ancients',
    'cardtype': 'minion',
    'tribe': 'Arcanyst',
    'cost': 7,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'The first spell you cast each turn costs 5 less.',
    'attack': 8,
    'health': 9,
    'spirit': None
  },
  {
    'cardid': 538,
    'name': 'Grandmaster Embla',
    'expansion': 'core',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text':
      '<b>Opening Gambit</b>: Surround the enemy General with random Walls.',
    'attack': 5,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 20359,
    'name': 'Ice Age',
    'expansion': 'mythron',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'Summon Blazing Spines along the outside of the battlefield.',
    'attack': None,
    'health': None,
    'spirit': None
  },
  {
    'cardid': 543,
    'name': 'Matron Elveiti',
    'expansion': 'unearthed',
    'cardtype': 'minion',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'Minions cannot attack your General.',
    'attack': 7,
    'health': 5,
    'spirit': None
  },
  {
    'cardid': 20212,
    'name': "Winter's Wake",
    'expansion': 'shimzar',
    'cardtype': 'spell',
    'tribe': '',
    'cost': 8,
    'rarity': 'legendary',
    'faction': 'vanar',
    'text': 'Give all friendly Wall minions +4/+4. Those minions can now move.',
    'attack': None,
    'health': None,
    'spirit': None
  }
]

with open('vanar.csv', 'w', newline='') as csvfile:
	w = csv.writer(csvfile)
	for d in cards:
		w.writerow([d['cardid']])
